GET http://localhost:3000/animals
Content-Type: application/json

###

POST http://localhost:3000/animals
Content-Type: application/json

{
    "name": "pes",
    "price": 10000,
    "categoryId": "2"
}

###

POST http://localhost:3000/categories
Content-Type: application/json

{
  "name": "vacnatec"
}

###

GET http://localhost:3000/categories
Content-Type: application/json

###
