name: Lokální API test přes self-hosted runner

on:
  workflow_dispatch:  # umožňuje spustit ručně z GitHubu

jobs:
  test-local-api:
    runs-on: self-hosted  # běží na tvém počítači, ne v cloudu

    steps:
      - name: Zobraz základní info o systému
        run: |
          echo "Uživatel: $env:USERNAME"
          echo "Stroj: $env:COMPUTERNAME"

      - name: Volání endpointu GET /animals
        run: |
          echo "Volání GET http://localhost:3000/animals"
          curl -X GET http://localhost:3000/animals
