name: Lokální API test přes self-hosted runner

on:
  workflow_dispatch:  # Umožňuje ruční spuštění z GitHubu

jobs:
  test-local-api:
    runs-on: self-hosted  # Běží na tvém Windows 11 stroji

    steps:
      - name: Zobraz základní info o systému
        run: |
          echo "Uživatel: $env:USERNAME"
          echo "Stroj: $env:COMPUTERNAME"

      - name: Ověření status kódu 200 při volání /animals
        run: |
          Write-Host "Volání http://localhost:3000/animals a kontrola status kódu"
          $status = & curl.exe -s -o $null -w "%{http_code}" http://localhost:3000/animals
          if ($status -ne 200) {
            Write-Host "Neočekávaný status kód: $status"
            exit 1
          } else {
            Write-Host "Status kód OK: $status"
          }

      - name: Výpis JSON odpovědi z GET /animals
        run: |
          Write-Host "Získaná odpověď z API:"
          & curl.exe -X GET http://localhost:3000/animals -H "Accept: application/json"
