name: Lokální API test přes self-hosted runner

on:
  workflow_dispatch:  # Umožňuje ruční spuštění z GitHubu

jobs:
  test-local-api:
    runs-on: self-hosted  # Běží na tvém Windows 11 stroji

    steps:
      - name: Zobraz základní info o systému
        run: |
          echo "Uživatel: $env:USERNAME"
          echo "Stroj: $env:COMPUTERNAME"

      - name: Výpis JSON odpovědi z GET /animals
        run: |
          Write-Host "Získaná odpověď z API:"
          & curl.exe -X GET http://localhost:3000/animals -H "Accept: application/json"
